### PR TITLE
Created test suite

### PR DESCRIPTION
**Pull request by AndrewCarterUK**
Should be good to go if you add this to Travis (Y)

### CODE REVIEW

**Comment by afilina** [comment]
This is great. It's like you read my mind :)

**Comment by AndrewCarterUK** [comment]
No worries, if you go to the [Travis CI](https://travis-ci.org/) website and add the repository it will automatically run the tests against pull requests to check they don't break the JSON.

It'll also make the nice shiny badge in the README file work and pester you with emails whenever you commit something that doesn't make it happy.

**Comment by afilina** [comment]
Ah yeah, totally forgot to flip the switch on Travis CI site. Thanks.

**Comment by afilina** [comment]
Just a head-up for @AndrewCarterUK in case you started using that data for a project: I just moved it to /data and renamed the repo to dev-community-data. I updated the tests too.

**Pull request merged**
